---

- include: setup_git_repo.yml
  tags: git

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_maintenance_pages.yml
  tags: templates

- include: setup_django_app.yml
  tags: django

- include: setup_uwsgi_ini.yml
  tags: uwsgi
